
    
const db = connect("localhost:27017/Project3");

const array = ['products', 'pcats', 'users', 'carts', 'inventories'];

array.forEach( v => { db[v].drop();});
array.forEach( v => { db.createCollection(v);});


db.pcats.insert(
  [
    { pcatid : "pcat-1" , pcatname : "Bread & Bakery", pcatdesc : "The best cupcakes, cookies, cheesecakes, fresh bread, muffins, bagels and more" },
    { pcatid : "pcat-2" , pcatname : "Dairy", pcatdesc : "Dairy products, milk products or lacticinia" },
    { pcatid : "pcat-6",  pcatname : "Take Away", pcatdesc: "Take away products"},
    { pcatid : "pcat-4",  pcatname : "Seafood", pcatdesc : "Crab, prawns and fishes"},
    { pcatid : "pcat-5",  pcatname : "Fruits & Vegetables", pcatdesc : "Fresh fruits and vegetables"},
    { pcatid : "pcat-3",  pcatname : "Canned Food", pcatdesc : ""},
    { pcatid : "pcat-7",  pcatname : "Meat & Poultry", pcatdesc : "Fresh Meat and Poultry"}
  ]
);


db.products.insert(
    [
        
        { pid : "p-1", pname : 'Crossaints', pdesc : 'A croissant is a buttery, flaky, viennoiserie pastry named for its crescent shape.', pcatid : "pcat-1"},
        { pid : "p-16",  pname : 'Cupcake', pdesc : 'Cinnamon apple studded cupcake with a gooey caramel butter cream frosting. ', pcatid : "pcat-1"},
        { pid : "p-2", pname : 'Pizza', pdesc : 'Pizza is a traditional Italian dish consisting of a yeasted flatbread typically topped with tomato sauce and cheese and baked in an oven.', pcatid : "pcat-1"},
        { pid : "p-3", pname : 'Milk', pdesc : 'Milk is the number one source of calcium. Milk is also fortified with vitamin D', pcatid : "pcat-2"},
        { pid : "p-4", pname : 'Cream Cheese', pdesc : 'Cream cheese is a soft, mild-tasting fresh cheese made from milk and cream.', pcatid : "pcat-2"},
        { pid : "p-5", pname : 'Egg', pdesc : 'Egg yolks and whole eggs store significant amounts of protein and choline and are widely used in cookery.', pcatid : "pcat-7"},
        { pid : "p-6", pname : 'Green Apples', pdesc : 'All apples have health benefits, but the thing that makes green apples special is that they have a high nutritional density packed with minerals.', pcatid : "pcat-5"},
        { pid : "p-7", pname : 'Peanut Butter', pdesc : 'Peanut butter is a food paste or spread made from ground dry roasted peanuts. It often contains additional ingredients that modify the taste or texture.', pcatid : "pcat-3"},
        { pid : "p-8", pname : 'Blueberry', pdesc : 'Blueberries are perennial flowering plants with blue– or purple–colored berries', pcatid : "pcat-5"},
        { pid : "p-9", pname : 'Banana split', pdesc : 'A banana split is an ice cream-based dessert. In its traditional form it is served in a long dish called a boat.', pcatid : "pcat-6"},
        { pid : "p-10", pname : 'Oysters', pdesc: 'Oysters are commonly consumed by humans, cooked or raw, and are regarded as a delicacy', pcatid: "pcat-4"},
        { pid : "p-11", pname : 'Jaggery',   pdesc : 'Jaggery is a concentrated product of cane juice and often date or palm sap without separation of the molasses and crystals.', pcatid : "pcat-3"},
        { pid : "p-12",  pname : 'Bread', pdesc : 'Bread is a staple food prepared from a dough of flour and water, usually by baking.', pcatid : "pcat-1"},
        { pid : "p-13",  pname : 'Shrimp', pdesc : 'Shrimp and prawn are important types of seafood that are consumed worldwide', pcatid : "pcat-4"},
        { pid : "p-14",  pname : 'Lasagne', pdesc : 'Lasagne  are wide, flat pasta, and possibly one of the oldest types of pasta.', pcatid : "pcat-6"},
        { pid : "p-15",  pname : 'Lobster', pdesc : 'Lobster recipes include perfect lobster rolls and decadent roasted lobsters with verjus and tarragon',  pcatid : "pcat-4" },
        { pid : "p-17", pname : 'Banana', pdesc: 'A banana is an edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants' , pcatid :  'pcat-5' },
        { pid : "p-18", pname : 'Salmon', pdesc : 'Salmon is the common name for several species of ray-finned fish in the family Salmonidae', pcatid : 'pcat-4'},
        { pid : "p-19", pname : 'Muffins', pdesc : 'Salmon is the common name for several species of ray-finned fish in the family Salmonidae', pcatid : 'pcat-1'},
        { pid : "p-20", pname : 'Strawberry', pdesc : 'The garden strawberry is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries', pcatid : 'pcat-5'},
        { pid : "p-21", pname : 'Capsicum', pdesc : 'Capsicum is a genus of flowering plants in the nightshade family Solanaceae', pcatid : 'pcat-5'},
        { pid : "p-22", pname : 'Butter', pdesc : 'With enough butter, anything is good.As long as you have these culinary building blocks hanging around, you can whip up everything from baked goods and luxurious sauces to the fluffiest scrambled eggs', pcatid : 'pcat-2'},
        { pid : "p-23", pname : 'Tuna', pdesc : 'Tuna has a high content of good fatty acids, vitamin D and is a good source of low fat protein.', pcatid : 'pcat-4'},
        { pid : "p-24", pname : 'Cheesecake', pdesc : 'Who ever said no to a delicious cheesecake?', pcatid : 'pcat-6'},
        { pid : "p-25", pname : 'Cookie', pdesc : 'A cookie a day keeps the sadness away. Chocolate Chip Cookies. Look no further!', pcatid : 'pcat-3'},
        { pid : "p-26", pname : 'Pickle', pdesc : 'Classic pickles you probably had growing up and may still eat today', pcatid : 'pcat-3'},
        { pid : "p-27", pname : 'Orange', pdesc : "Oranges might seem like an ordinary fruit, but there's much more to them than just their color.", pcatid : 'pcat-5'},
        { pid : "p-28", pname : 'Carrot', pdesc : 'Raw carrot sticks are a nutritious way to enjoy the vegetable. Eating the carrot sticks with a variety of dips can boost your intake of vitamins and minerals.', pcatid : 'pcat-5'},
        { pid : "p-29", pname : 'Donuts', pdesc : 'A doughnut (British) or donut (American) is a type of fried dough confection or dessert food.', pcatid : 'pcat-3'},
        { pid : "p-30", pname : 'Crab', pdesc : 'The soft shelled crab and the steamed fish with pad thai are a relief', pcatid : 'pcat-4'},
        { pid : "p-31", pname : 'Cornflakes', pdesc : 'Corn flakes, or cornflakes, is a breakfast cereal made by toasting flakes of corn (maize). The cereal was created by John Harvey Kellogg in 1894.', pcatid : 'pcat-3'},
        { pid : "p-32", pname : 'Cheese', pdesc : 'Cheese is a dairy product derived from milk that is produced in a wide range of flavors, textures, and forms by coagulation of the milk protein casein. ', pcatid : 'pcat-2'},
        { pid : "p-33", pname : 'Mango', pdesc : 'Mangoes are juicy stone fruit (drupe) from numerous species of tropical trees belonging to the flowering plant genus Mangifera, cultivated mostly for their edible fruit.', pcatid : 'pcat-5'},
        { pid : "p-34", pname : 'Brownies', pdesc : 'A chocolate brownie is a square, baked, chocolate dessert.', pcatid : 'pcat-3'},
        { pid : "p-35", pname : 'Fruit Jam', pdesc : 'Fruit jam typically contains both the juice and flesh of a fruit', pcatid : 'pcat-3'},
        { pid : "p-36", pname : 'Pan Cake', pdesc : 'A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface such as a griddle or frying pan, often frying with oil or butter.', pcatid : 'pcat-6'},
        { pid : "p-37", pname : 'Peach', pdesc : 'A peach is a soft, juicy and fleshy stone fruit produced by a peach tree.', pcatid : 'pcat-5'},
        { pid : "p-38", pname : 'Pineapple', pdesc : 'The pineapple (Ananas comosus) is a tropical plant with an edible multiple fruit consisting of coalesced berries, also called pineapples.', pcatid : 'pcat-5'},
        { pid : "p-39", pname : 'Potato', pdesc : 'The potato is a starchy, tuberous crop from the perennial nightshade Solanum tuberosum. ', pcatid : 'pcat-5'},
        { pid : "p-40", pname : 'Rabbit', pdesc : ' Rabbit meat is  both succulent and flavoursome, and combines both healthy eating and good flavours', pcatid : 'pcat-7'},
        { pid : "p-41", pname : 'Raspberry', pdesc : 'The raspberry is the edible fruit of a multitude of plant species in the genus Rubus of the rose family', pcatid : 'pcat-5'},
        { pid : "p-42", pname : 'Red Chilli', pdesc : 'The chili pepper from Nahuatl chīlli is the fruit of plants from the genus Capsicum', pcatid : 'pcat-5'},
        { pid : "p-43", pname : 'Spring Roll', pdesc : 'Spring rolls are a large variety of filled, rolled appetizers or dim sum found in East Asian, South Asian, and Southeast Asian cuisine.', pcatid : 'pcat-6'},
        { pid : "p-44", pname : 'Sushi', pdesc : 'Sushi is a Japanese dish of specially prepared vinegared rice, usually with some sugar and salt, combined with a variety of ingredients', pcatid : 'pcat-6'},
        { pid : "p-45", pname : 'Tacos', pdesc : 'The more you run the more tacos you can eat.', pcatid : 'pcat-6'},
        { pid : "p-46", pname : 'Tomato', pdesc : 'Tomatoes are the fourth most popular fresh-market vegetable behind potatoes', pcatid : 'pcat-5'},
        { pid : "p-47", pname : 'Veg Cheese Sandwich', pdesc : 'Delicious cheesiest vegetable sandwich which taste so delicious.', pcatid : 'pcat-6'},
        { pid : "p-48", pname : 'Watermelon', pdesc : 'Watermelons are mostly water — about 92 percent — this refreshing fruit is soaked with nutrients', pcatid : 'pcat-5'},
        { pid : "p-49", pname : 'Mutton', pdesc : 'Mutton is a treat to any Non vegetarian food lover. From basic roasted leg of lamb to exotic dishes, the cooking options multiply', pcatid : 'pcat-7'},
        { pid : "p-50", pname : 'Mushroom', pdesc : 'Edible mushrooms are the fleshy and edible fruit bodies of several species of macrofungi', pcatid : 'pcat-5'},
        { pid : "p-51", pname : 'Onion Ring', pdesc : 'Onion rings are a form of appetizer or side dish commonly found in the United States, Canada, United Kingdom, Ireland, Australia, New Zealand, South Africa and some parts of Asia, Continental Europe, and Latin America.', pcatid : 'pcat-6'},
        { pid : "p-52", pname : 'Broccli', pdesc : 'Broccoli is an edible green plant in the cabbage family whose large flowering head is eaten as a vegetable.The word broccoli comes from the Italian plural of broccolo, which means the flowering crest of a cabbage.', pcatid : 'pcat-5'},
        { pid : "p-53", pname : 'Onion', pdesc : 'The onion, also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium', pcatid : 'pcat-5'},
        { pid : "p-54", pname : 'Milkshake', pdesc : 'A milkshake is a sweet, cold beverage that is usually made from milk, ice cream, or iced milk, and flavorings or sweeteners such as butterscotch, caramel sauce, chocolate syrup, or fruit syrup.', pcatid : 'pcat-6'},
        { pid : "p-55", pname : 'Curd', pdesc : 'Curds are a dairy product obtained by coagulating milk in a process called curdling.', pcatid : 'pcat-2'},
        { pid : "p-56", pname : 'Oats', pdesc : 'Oats are a nutrient-rich food associated with lower blood cholesterol when consumed regularly.', pcatid : 'pcat-3'},
        { pid : "p-57", pname : 'Momos', pdesc : 'Momo is a type of South Asian dumpling; native to Bhutan, Tibet, Nepal, North Indian region of Ladakh, Northeast Indian regions of Sikkim, Assam, and Arunachal Pradesh, and Darjeeling, West Bengal, India.', pcatid : 'pcat-6'},
        { pid : "p-58", pname : 'Duckling', pdesc : 'Duck meat is a very flavorful type of poultry.', pcatid : 'pcat-7'},
        { pid : "p-59", pname : 'Chicken', pdesc : 'Chicken is the most common type of poultry in the world.', pcatid : 'pcat-7'},
        { pid : "p-60", pname : 'Samosa', pdesc : 'A samosa is a fried(usually) or baked dish with a savoury filling, such as spiced potatoes, onions, peas, or lentils. Its size and consistency may vary, but typically it is distinctly triangular or tetrahedral in shape.', pcatid : 'pcat-6'},
        { pid : "p-61", pname : 'Corn', pdesc : 'Corn is a cereal grain first domesticated by indigenous peoples in southern Mexico about 10,000 years ago.', pcatid : 'pcat-5'},
        { pid : "p-62", pname : 'Guava', pdesc : 'Guavas are common tropical fruits cultivated and enjoyed in many tropical and subtropical regions.', pcatid : 'pcat-5'},
        { pid : "p-63", pname : 'Burrito', pdesc : 'Burrito is a dish in Mexican and Tex-Mex cuisine that consists of a flour tortilla with various other ingredients.', pcatid : 'pcat-6'},
        { pid : "p-64", pname : 'Bagel', pdesc : 'Bagel also spelled beigel, is a bread product originating in the Jewish communities of Poland.', pcatid : 'pcat-1'}
     ]
);

db.inventories.insert(
    [
        { inventoryid : "inv-1", productid : "p-1", quantity : 200 , price : 0.5},
        { inventoryid : "inv-2", productid : "p-2", quantity : 50 , price : 2.5},
        { inventoryid : "inv-3", productid : "p-3", quantity : 200 , price : 1.5},
        { inventoryid : "inv-4", productid : "p-4", quantity : 200 , price : 2.21},
        { inventoryid : "inv-5", productid : "p-5", quantity : 200 , price : 0.5},
        { inventoryid : "inv-6", productid : "p-6", quantity : 200 , price : 1.0},
        { inventoryid : "inv-7", productid : "p-7", quantity : 200 , price : 1.2},
        { inventoryid : "inv-8", productid : "p-8", quantity : 200 , price : 1.0},
        { inventoryid : "inv-9", productid : "p-9", quantity : 200 , price : 1.0},
        { inventoryid : "inv-10", productid : "p-10", quantity : 200 , price : 4.0},
        { inventoryid : "inv-11", productid : "p-11", quantity : 200 , price : 1.0},
        { inventoryid : "inv-12", productid : "p-12", quantity : 200 , price : 0.5},
        { inventoryid : "inv-13", productid : "p-13", quantity : 50 , price : 2.5},
        { inventoryid : "inv-14", productid : "p-14", quantity : 200 , price : 1.5},
        { inventoryid : "inv-15", productid : "p-15", quantity : 200 , price : 2.2},
        { inventoryid : "inv-16", productid : "p-16", quantity : 200 , price : 0.75},
        { inventoryid : "inv-17", productid : "p-17", quantity : 200 , price : 3.25},
        { inventoryid : "inv-18", productid : "p-18", quantity : 50 , price : 2.5},
        { inventoryid : "inv-19", productid : "p-19", quantity : 200 , price : 1.15},
        { inventoryid : "inv-20", productid : "p-20", quantity : 300 , price : 2.27},
        { inventoryid : "inv-21", productid : "p-21", quantity : 200 , price : 0.5},
        { inventoryid : "inv-22", productid : "p-22", quantity : 200 , price : 1.0},
        { inventoryid : "inv-23", productid : "p-23", quantity : 200 , price : 1.2},
        { inventoryid : "inv-24", productid : "p-24", quantity : 200 , price : 1.0},
        { inventoryid : "inv-25", productid : "p-25", quantity : 200 , price : 1.0},
        { inventoryid : "inv-26", productid : "p-26", quantity : 200 , price : 4.0},
        { inventoryid : "inv-27", productid : "p-27", quantity : 200 , price : 1.0},
        { inventoryid : "inv-28", productid : "p-28", quantity : 200 , price : 0.5},
        { inventoryid : "inv-29", productid : "p-29", quantity : 50 , price : 2.5},
        { inventoryid : "inv-30", productid : "p-30", quantity : 200 , price : 1.5},
        { inventoryid : "inv-31", productid : "p-31", quantity : 200 , price : 2.2},
        { inventoryid : "inv-32", productid : "p-32", quantity : 200 , price : 0.75},
        { inventoryid : "inv-33", productid : "p-33", quantity : 200 , price : 0.5},
        { inventoryid : "inv-34", productid : "p-34", quantity : 50 , price : 2.5},
        { inventoryid : "inv-35", productid : "p-35", quantity : 200 , price : 1.5},
        { inventoryid : "inv-36", productid : "p-36", quantity : 200 , price : 2.2},
        { inventoryid : "inv-37", productid : "p-37", quantity : 200 , price : 0.5},
        { inventoryid : "inv-38", productid : "p-38", quantity : 200 , price : 1.0},
        { inventoryid : "inv-39", productid : "p-39", quantity : 200 , price : 17.2},
        { inventoryid : "inv-40", productid : "p-40", quantity : 200 , price : 1.0},
        { inventoryid : "inv-9", productid : "p-41", quantity : 200 , price : 1.0},
        { inventoryid : "inv-10", productid : "p-42", quantity : 200 , price : 4.0},
        { inventoryid : "inv-11", productid : "p-43", quantity : 200 , price : 1.0},
        { inventoryid : "inv-12", productid : "p-44", quantity : 200 , price : 0.5},
        { inventoryid : "inv-13", productid : "p-45", quantity : 50 , price : 2.5},
        { inventoryid : "inv-14", productid : "p-46", quantity : 200 , price : 1.5},
        { inventoryid : "inv-15", productid : "p-47", quantity : 200 , price : 2.25},
        { inventoryid : "inv-16", productid : "p-48", quantity : 200 , price : 0.75},
        { inventoryid : "inv-1", productid : "p-49", quantity : 200 , price : 0.82},
        { inventoryid : "inv-2", productid : "p-50", quantity : 50 , price : 2.5},
        { inventoryid : "inv-3", productid : "p-51", quantity : 200 , price : 1.5},
        { inventoryid : "inv-4", productid : "p-52", quantity : 200 , price : 2.2},
        { inventoryid : "inv-5", productid : "p-53", quantity : 200 , price : 0.5},
        { inventoryid : "inv-6", productid : "p-54", quantity : 200 , price : 1.0},
        { inventoryid : "inv-7", productid : "p-55", quantity : 200 , price : 1.2},
        { inventoryid : "inv-8", productid : "p-56", quantity : 200 , price : 1.0},
        { inventoryid : "inv-9", productid : "p-57", quantity : 200 , price : 1.07},
        { inventoryid : "inv-10", productid : "p-58", quantity : 200 , price : 4.0},
        { inventoryid : "inv-11", productid : "p-59", quantity : 200 , price : 1.0},
        { inventoryid : "inv-12", productid : "p-60", quantity : 200 , price : 0.5},
        { inventoryid : "inv-13", productid : "p-61", quantity : 50 , price : 2.5},
        { inventoryid : "inv-14", productid : "p-62", quantity : 200 , price : 1.5},
        { inventoryid : "inv-15", productid : "p-63", quantity : 200 , price : 2.2},
        { inventoryid : "inv-16", productid : "p-64", quantity : 200 , price : 0.75},
    ]
);


